# Generated by Django 4.2.16 on 2024-11-15 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tempo_de_preparo', models.IntegerField()),
                ('foto', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas_obs', to=settings.AUTH_USER_MODEL)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.receita')),
            ],
        ),
    ]
